set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_5bits_tri_i[0]}]
set_property PACKAGE_PIN T18 [get_ports {btns_5bits_tri_i[0]}]
set_property PACKAGE_PIN R18 [get_ports {btns_5bits_tri_i[1]}]
set_property PACKAGE_PIN R16 [get_ports {btns_5bits_tri_i[2]}]
set_property PACKAGE_PIN P16 [get_ports {btns_5bits_tri_i[3]}]
set_property PACKAGE_PIN N15 [get_ports {btns_5bits_tri_i[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_8bits_tri_o[7]}]
set_property PACKAGE_PIN T22 [get_ports {leds_8bits_tri_o[0]}]
set_property PACKAGE_PIN T21 [get_ports {leds_8bits_tri_o[1]}]
set_property PACKAGE_PIN U22 [get_ports {leds_8bits_tri_o[2]}]
set_property PACKAGE_PIN U21 [get_ports {leds_8bits_tri_o[3]}]
set_property PACKAGE_PIN V22 [get_ports {leds_8bits_tri_o[4]}]
set_property PACKAGE_PIN W22 [get_ports {leds_8bits_tri_o[5]}]
set_property PACKAGE_PIN U19 [get_ports {leds_8bits_tri_o[6]}]
set_property PACKAGE_PIN U14 [get_ports {leds_8bits_tri_o[7]}]

